dist: bionic
language: python
python:
  - 3.6
cache: pip
services:
env:
  - SCRIPT="./manage.py --squad-host http://localhost:9000 test -v"
install:
  - pip install -r requirements-dev.txt
script:
  - $SCRIPT
