#!/bin/sh

set -eu

v="$1"

# Push to PyPi
# sign & upload
for f in dist/*; do
    gpg --detach-sign --armor "$f"
done
twine upload dist/*

# Push to dockerhub
echo 'Login to hub.docker.com:'
docker login
docker push squadproject/squad-client:$v
docker push squadproject/squad-client:latest

# Push to github
git tag -s -m "SQUAD Client release $v" "$v"
git push
git push --tags

rm -rf build/
rm -rf dist/
rm -rf *.egg-info/
